### ISSUE TITLE
[BUG] A mission failed!

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#190]
[TLDRMissions.zip](https://github.com/teelolws/TLDRMissions/files/8689097/TLDRMissions.zip)

2226 failed, 9.2-053 patch

**Comment by teelolws** [comment]
Looks like whatever made it fail was fixed in 054. The simulator matches the result

**Comment by zeenk** [comment]
Ah ok, it was a mission from last night that wasn't ready before I went to bed so thought I might as well send it to u incase it was not fixed already ^^
